service: recording-disclosures-polly 
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1 
  role: arn:aws:iam::439077922257:role/recording-disclosures-role
      
functions:
  speak:
    handler: handler.speak
    events:
      - http: 
          path: speak
          method: post
          cors: true